; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=(Cherepavel Rimsky)
AppVersion=(2.0)
DefaultDirName={pf}\(Cherepavel Rimsky)
DefaultGroupName=(Cherepavel Rimsky)

[Files]
Source: "D:\Practice\Practice_sharp\28\Task-1\bin\Release\Task1.exe"; DestDir: "{app}"

